# Generated by Django 4.1.1 on 2022-10-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figuritas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figus_totales',
            name='user',
        ),
    ]
